version: "3"
services:
    large_file_processor:
        container_name: large_file_processor
        build:
            context: .
            dockerfile: Dockerfile
        image: kunal-large_file_processor
        volumes:
            - type: bind
              source: demo/target
              target: /app
        network_mode: "host"
        restart: always